//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VintageCars.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class ImageTbl
    {
        public int Id { get; set; }
        public string Image_url { get; set; }
        public string CarPicture { get; set; }

        [Required(ErrorMessage = "Title Is Required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Choose File")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase editPostedFile { get; set; }

        public System.DateTime Date { get; set; }
        public string Extension { get; set; }
    }
}
