//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VintageCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTbl
    {
        public int Id { get; set; }
        public string Image_url { get; set; }
        public string ServicePicture { get; set; }
        public string Title { get; set; }
        public string Extension { get; set; }
        public System.DateTime Date { get; set; }
    }
}
